spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      authentication-database: admin
      username: root
      password: example
      database: circuit-breaker

client:
  comments:
    url: http://localhost:8082


resilience4j.circuitbreaker:
  instances:
    comments:
      slidingWindowSize: 8
      minimumNumberOfCalls: 4
#      slowCallDurationThreshold: 2000
#      slowCallRateThreshold: 20
#      permittedNumberOfCallsInHalfOpenState: 2
#      waitDurationInOpenState: 10000
